[package]
name = "rulsp"
version = "0.1.0"
authors = ["arathunku <arathunku@gmail.com>"]

[dependencies]
regex = "0.1.77"
lazy_static = "0.1.*"
rustyline = "1.0.0"
fnv = "1.0.3"
log = "0.3"
env_logger = "0.3"

[profile.release]
debug = true
lto = true
